name: Main
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: '0 0 * * 6'

  workflow_dispatch:

jobs:
  main:
    strategy:
      fail-fast: false
      matrix:
        config:
          - name: 'macos'
            image: 'macos-12'
            solution: 'XamlMath.Portable.sln'
          - name: 'linux'
            image: 'ubuntu-22.04'
            solution: 'XamlMath.Portable.sln'
          - name: 'windows'
            image: 'windows-2022'
            solution: 'XamlMath.All.sln'

    name: main.${{ matrix.config.name }}
    runs-on: ${{ matrix.config.image }}

    env:
      DOTNET_NOLOGO: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      NUGET_PACKAGES: ${{ github.workspace }}/.github/nuget-packages

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Verify encoding
        shell: pwsh
        run: ./scripts/verify-encoding.ps1

      - name: NuGet cache
        uses: actions/cache@v3
        with:
          path: ${{ env.NUGET_PACKAGES }}
          key: ${{ runner.os }}.nuget.${{ hashFiles('**/*.csproj') }}

      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            3.1.x
            5.0.x
            7.0.x

      - name: Build
        run: dotnet build ${{ matrix.config.solution }}

      - name: Pack
        run: dotnet pack ${{ matrix.config.solution }}

      - name: Test
        run: dotnet test ${{ matrix.config.solution }}
