name: NuGet
on:
  push:
    tags:
      - 'v*'

  workflow_dispatch:

jobs:
  nuget-push:
    runs-on: 'windows-2022'
    env:
      DOTNET_NOLOGO: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      NUGET_PACKAGES: ${{ github.workspace }}/.github/nuget-packages
    steps:
      - name: Read version from ref
        id: version
        shell: pwsh
        run: Write-Output "::set-output name=version::$($env:GITHUB_REF -replace '^refs/tags/v', '')"

      - name: Checkout
        uses: actions/checkout@v3

      - name: NuGet cache
        uses: actions/cache@v3
        with:
          path: ${{ env.NUGET_PACKAGES }}
          key: release.nuget.${{ hashFiles('**/*.csproj') }}

      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'

      - name: Prepare a NuGet package
        run: dotnet pack --configuration Release -p:Version=${{ steps.version.outputs.version }}

      - name: Read changelog
        id: changelog
        uses: ForNeVeR/ChangelogAutomation.action@v1
        with:
          output: ./release-notes.md

      - name: Create release
        id: release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: WPF-Math v${{ steps.version.outputs.version }}
          body_path: ./release-notes.md

      - name: Upload WPF-Math .nupkg file
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_name: WpfMath.${{ steps.version.outputs.version }}.nupkg
          asset_path: ./src/WpfMath/bin/Release/WpfMath.${{ steps.version.outputs.version }}.nupkg
          asset_content_type: application/zip

      - name: Upload Avalonia-Math .nupkg file
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_name: AvaloniaMath.${{ steps.version.outputs.version }}.nupkg
          asset_path: ./src/AvaloniaMath/bin/Release/AvaloniaMath.${{ steps.version.outputs.version }}.nupkg
          asset_content_type: application/zip

      - name: Upload WPF-Math .snupkg file
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_name: WpfMath.${{ steps.version.outputs.version }}.snupkg
          asset_path: ./src/WpfMath/bin/Release/WpfMath.${{ steps.version.outputs.version }}.snupkg
          asset_content_type: application/zip

      - name: Upload Avalonia-Math .snupkg file
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_name: AvaloniaMath.${{ steps.version.outputs.version }}.snupkg
          asset_path: ./src/AvaloniaMath/bin/Release/AvaloniaMath.${{ steps.version.outputs.version }}.snupkg
          asset_content_type: application/zip

      - name: Push WPF-Math package to NuGet
        run: dotnet nuget push ./src/WpfMath/bin/Release/WpfMath.${{ steps.version.outputs.version }}.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_TOKEN_WPF }}

      - name: Push Avalonia-Math package to NuGet
        run: dotnet nuget push ./src/AvaloniaMath/bin/Release/AvaloniaMath.${{ steps.version.outputs.version }}.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_TOKEN_AVALONIA }}
